services:
  frontend:
    build:
      context: ./frontend
    platform: linux/arm64
    image: minjegod/linux_gui_frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    build:
      context: ./backend
    image: minjegod/linux_gui_backend:latest
    platform: linux/arm64
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL
      - SECRET_KEY
      - ALGORITHM
    privileged: false
    volumes:
      - /var/log:/var/log:ro
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s