user nginx;
worker_processes auto; #cpu를 감지하여 코어수에 맞추어 프로세스 설정
error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

events {
    worker_connections 1024; #각 프로세스가 동시에 1024개의 연결 처리 가능
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;
    client_max_body_size 20M; #파일 업로드 용량을 20MB로 제한

    gzip on;    #텍스트 데이터를 압축해서 보냄
    gzip_vary on;
    gzip_comp_level 6;
    gzip_types text/plain text/css text/javascript application/json;

    limit_req_zone $binary_remote_addr zone=general:10m rate=10r/s;  #동일한 ip에서 초당 10개의 요청을 처리하도록 제한(디도스 방어)
  
    
    upstream api_backend { #컨테이터 이름(backend)이 도커 네트워크 상에서 IP로 변환되는 과정
        server backend:8000; #backend이름으로 요청시 8000포트로 전달
    }

    server {
        listen 80; #기본 웹 포트 80번
        server_name _;

        location / {
            root /usr/share/nginx/html; #접속 시 기본 html 파일이 있는 경로
            try_files $uri $uri/ /index.html; #요청된 파일이 없으면 index.html로 전달 vite/react 배포시 필수 설정
            expires 1d; #정적 파일에 대한 캐시 설정, 1일 동안 다시 요청하지 않도록 브라우저에 지시
        }

        location /api/ { #주소에서 /api/ 요청을 보고 어느 컨테이너로 전달(proxy)할지 결정
            limit_req zone=general burst=20 nodelay;
            proxy_pass http://api_backend; # /api/요청은 api_backend로 전달
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;    #사용자의 실제 IP 주소를 백엔드로 전달
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Connection "";
        }

        location /health { #헬스체크 엔드포인트
            access_log off;
            return 200 "healthy\n";
        }
    }
}
